apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: system-surge
  annotations:
    kubernetes.io/description: "Surge capacity pool for system pod pressure"
spec:
  # Resource limits to constrain the total size of the system pool
  # Following Microsoft's recommendation for high availability system nodes
  limits:
    cpu: "48"        # Total CPU across all system nodes (6 nodes * 8 vCPUs)
    memory: 192Gi    # Total memory across all system nodes (6 nodes * 32GB)
    minSize: 1       # Minimum 3 nodes for high availability
    maxSize: 6       # Maximum nodes to control costs while maintaining availability
  # Disruption settings for cost-effective bin-packing without jeopardizing workloads
  disruption:
    budgets:
    - nodes: 10%     # Conservative disruption - only 10% of nodes at once
    # Microsoft recommendation: 30s consolidateAfter for sensible cost optimization
    consolidateAfter: 30s
    # WhenEmptyOrUnderutilized enables cost-effective bin-packing
    consolidationPolicy: WhenEmptyOrUnderutilized
  template:
    metadata:
      labels:
        kubernetes.azure.com/ebpf-dataplane: cilium
        kubernetes.azure.com/mode: system
    spec:
      expireAfter: Never
      nodeClassRef:
        group: karpenter.azure.com
        kind: AKSNodeClass
        name: default
      requirements:
      # Architecture and OS requirements
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      # Capacity type: on-demand for system workloads (high availability)
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
      - key: karpenter.azure.com/sku-family
        operator: In
        values:
        - D
      startupTaints:
      - effect: NoExecute
        key: node.cilium.io/agent-not-ready
        value: "true"
      taints:
      - effect: NoSchedule
        key: CriticalAddonsOnly
        value: "true"